meta:
  sensor:
    # Time step for simulator.
    time_step: 0.005

    # Sensor radius.
    sensor_radius: 1.0

    # Number of obstacles.
    num_obstacles: 0

  control:
    # Interval (seconds) of the discrete-time control update.
    time_step: 0.01

    # Control dimension.
    dim: 3

    # Upper and lower bounds for control.
    # In the quadrotor 6D model, the controls are [thrust, roll, pitch].
    upper: [0.2618, 0.2618, 16.0]
    lower: [-0.2618, -0.2618, 4.0]

  state:
    # Full (tracker) state space dimension.
    dim: 6

    # Upper and lower bounds for state space.
    # In the quadrotor 6D model, state is [x, y, z, vx, vy, vz].
    upper: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    lower: [-10.0, -10.0, 0.0, -10.0, -10.0, -10.0]

  planners:
    # Directories in which subsystem value functions are stored.
    # These are assumed to be in the PRECOMPUTATION_DIR directory, and to
    # end in a '/' so that raw filenames can be concatenated directly.
    values: [speed_1_tenths/]

  meta:
    # Max connection radius for meta planner.
    max_connection_radius: 10.0

  topics:
    # Sensor publication topic.
    sensor: /sensor

    # State estimator topic.
    state: /state

    # Reference to track.
    reference: /reference

    # Visualization topics.
    traj: /vis/traj
    true_environment: /vis/true_env
    known_environment: /vis/known_env
    tracking_bound: /vis/bound
    sensor_radius: /vis/sensor

    # Control topic.
    control: /control/optimal

  frames:
    # Fixed frame.
    fixed: fixed

    # Tracker frame.
    tracker: tracker

    # Planner frame.
    planner: planner
