meta_planner:
  topics:
    # Sensor publication topic.
    sensor: sensor

    # Visualization topics.
    rrt_connect: rrt_connect

  frames:
    # Fixed frame.
    fixed: fixed

    # Tracker frame.
    tracker: tracker
