meta_planner:
  control:
    # Interval (seconds) of the discrete-time control update.
    time_step: 1.0

  topics:
    # Sensor publication topic.
    sensor: /sensor

    # Visualization topic.
    rrt_connect: /rrt_connect
    vis: /vis

    # Control topic.
    control: /control

  frames:
    # Fixed frame.
    fixed: fixed

    # Tracker frame.
    tracker: tracker

  state_space:
    dimension: 3
